import { NgModule } from '@angular/core';

import { MatAutocompleteModule } from '@angular/material/autocomplete';
import {  MatInputModule,
          MatCheckboxModule,
          MatButtonModule,
          MatListModule,
          MatToolbarModule,
          MatTabsModule,
          MatExpansionModule,
          MatCardModule,
          MatDialogModule,
          MatBadgeModule,
          MatSnackBarModule,
          MatFormFieldModule,
          MatTableModule,
          MatIconModule,
          MatDividerModule,
          MatChipsModule,
          MatTooltipModule,
          MatProgressBarModule,
          MatSelectModule,
          MatOptionModule,
          MatGridListModule } from '@angular/material';

import { FlexLayoutModule } from '@angular/flex-layout';

@NgModule({
  imports: [
  	FlexLayoutModule,
    MatAutocompleteModule,
    MatInputModule,
	MatCheckboxModule,
	MatButtonModule,
	MatListModule,
	MatToolbarModule,
	MatTabsModule,
	MatExpansionModule,
	MatCardModule,
	MatDialogModule,
	MatBadgeModule,
	MatSnackBarModule,
	MatFormFieldModule,
	MatTableModule,
	MatIconModule,
	MatDividerModule,
	MatChipsModule,
	MatTooltipModule,
	MatProgressBarModule,
	MatSelectModule,
	MatOptionModule,
	MatGridListModule
  ],
  exports: [
  	FlexLayoutModule,
    MatAutocompleteModule,
    MatInputModule,
	MatCheckboxModule,
	MatButtonModule,
	MatListModule,
	MatToolbarModule,
	MatTabsModule,
	MatExpansionModule,
	MatCardModule,
	MatDialogModule,
	MatBadgeModule,
	MatSnackBarModule,
	MatFormFieldModule,
	MatTableModule,
	MatIconModule,
	MatDividerModule,
	MatChipsModule,
	MatTooltipModule,
	MatProgressBarModule,
	MatSelectModule,
	MatOptionModule,
	MatGridListModule
  ]
})
export class MaterialModule { }
